### ISSUE TITLE
url does not connect

### ISSUE THREAD

**Issue by adatamonk** [kquinsland/skyhole#1]
hi there, the script setup works great, however i cannot seem to get the device to connect to the URL. any updates to this project to fix this?

**Comment by kquinsland** [comment]
I don't understand your question.  `device` is your phone? and the `URL` is?

**Comment by adatamonk** [comment]
hey there, thanks for your reply. 

Basically followed your setup - made modifications to traefik.toml, pihole.env & docker-compose.yaml

Ran bootstrap - all well - subdomain I picked `pihole.mydomain.com` loads the dashboard.

However, when I added `pihole.mydomain.com` to my android private DNS setting it does not connect. Might be coreDNS not working as intended?

**Comment by kquinsland** [comment]
Gotcha.

I spent quite a bit of time with `adb logcat` to keep an eye on why Android didn't connect. It's been a while, so i don't remember what filters i used to tame the fire hose of logs. I do remember turning the custom DNS on and then seeing a lot of relevant logs fly past... so that's probably a good place to start. If memory serves, the errors were pretty cryptic and i had to do a ton of grepping through the openssl code to figure out errors... but in the end, it ended up being two things:

- must be port 443, standard for https
- mist have a certificate that's "valid" and trusted by a system CA.


 use `openssl s_client` to make sure that something is listening on your server and that the certificate that comes back is valid.

a quick google turns this up as good next steps:
https://medium.com/@nykolas.z/troubleshooting-dns-over-tls-e7ca570b6337

Assuming that you have a working TLS server on the other end that serves a trusted cert, `kdig` is the tool that i used to troubleshoot the TLS -> piHole segment

https://www.knot-dns.cz/docs/2.6/html/man_kdig.html

**Comment by adatamonk** [comment]
i was actually successful in getting erised running - but I am not sure how to enable the pihole web interface so I can access it remotely? would you have any suggestions?

**Comment by kquinsland** [comment]
I don't know what. `erised` is, but `docker logs -f $container_name` will be your best bet for troubleshooting. PiHole has no hard dependencies, so if it came up, then `traefik` is what you need to look at next as that's the proxy between pihole's web interface and your browser.

**Comment by adatamonk** [comment]
you mentioned `erised` in your readme which is where i found it from :)

https://github.com/eldridgea/erised

Since I have this running, and you based yours on this, i wondered if you knew how to enable piholes web interface on that?

**Comment by kquinsland** [comment]
Ah.  To be clear; nothing about skyhole is based on `erised`. Just a very similar project that implements the same basic function.

I don't use `caddy`, i use `traefik` ... etc.

**Comment by kquinsland** [comment]
@agamus  I did a quick check; the `Corefile` that i run in production is *slightly* different from the one that was in `Master`.

Please make sure your `Corefile` is updated to reflect the changes made here:

https://github.com/kquinsland/skyhole/commit/da87d09911b1dc8f18ef6c3ee92a31f87c0c3008#diff-c643166f59d17462b67ca1b9ba4e0bc3


and that should be all that's needed to get up and running.

**Comment by adatamonk** [comment]
thank you, 1 last question - do we need to put the server's public static IP address in this location?

https://github.com/kquinsland/skyhole/blob/master/docker/env/pi.public_ip.env

I was not sure on this and the guide does not say to do anything here?

**Comment by kquinsland** [comment]
Yes, it should have already been done.

https://github.com/kquinsland/skyhole/blob/f272f813b14fc409c4a0226dfac1b860eaf3acd2/bootstrap.sh#L98

**Comment by adatamonk** [comment]
appreciate the help @kquinsland - i'll give it a go
